repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v.0961'
  hooks:
  -   id: mypy